name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test default feature set (std based)
      run: cargo test --features std --verbose   
    - name: Test default feature set (no std based)
      run: cargo test --features no_std --verbose
